/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PropertyRegistry {
  export type TransferRequestStruct = {
    transferId: BigNumberish;
    propertyId: BigNumberish;
    fromOwner: AddressLike;
    toOwner: AddressLike;
    requestTimestamp: BigNumberish;
    isApproved: boolean;
    isRejected: boolean;
    rejectionReason: string;
  };

  export type TransferRequestStructOutput = [
    transferId: bigint,
    propertyId: bigint,
    fromOwner: string,
    toOwner: string,
    requestTimestamp: bigint,
    isApproved: boolean,
    isRejected: boolean,
    rejectionReason: string
  ] & {
    transferId: bigint;
    propertyId: bigint;
    fromOwner: string;
    toOwner: string;
    requestTimestamp: bigint;
    isApproved: boolean;
    isRejected: boolean;
    rejectionReason: string;
  };

  export type PropertyStruct = {
    propertyId: BigNumberish;
    surveyNumber: string;
    location: string;
    areaInSqFt: BigNumberish;
    currentOwner: AddressLike;
    ipfsDocumentHash: string;
    isVerified: boolean;
    registrationTimestamp: BigNumberish;
    propertyType: BigNumberish;
    description: string;
  };

  export type PropertyStructOutput = [
    propertyId: bigint,
    surveyNumber: string,
    location: string,
    areaInSqFt: bigint,
    currentOwner: string,
    ipfsDocumentHash: string,
    isVerified: boolean,
    registrationTimestamp: bigint,
    propertyType: bigint,
    description: string
  ] & {
    propertyId: bigint;
    surveyNumber: string;
    location: string;
    areaInSqFt: bigint;
    currentOwner: string;
    ipfsDocumentHash: string;
    isVerified: boolean;
    registrationTimestamp: bigint;
    propertyType: bigint;
    description: string;
  };
}

export interface PropertyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "approveTransfer"
      | "getOwnerProperties"
      | "getPendingTransfer"
      | "getPropertyDetails"
      | "governmentAuthority"
      | "initialize"
      | "initiateTransfer"
      | "ownerProperties"
      | "pause"
      | "paused"
      | "properties"
      | "propertyCount"
      | "propertyPendingTransfer"
      | "proxiableUUID"
      | "registerProperty"
      | "rejectProperty"
      | "rejectTransfer"
      | "surveyNumberExists"
      | "transferRequestCount"
      | "transferRequests"
      | "unpause"
      | "updateGovernmentAuthority"
      | "upgradeToAndCall"
      | "verifyProperty"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GovernmentAuthorityUpdated"
      | "Initialized"
      | "OwnershipTransferred"
      | "Paused"
      | "PropertyRegistered"
      | "PropertyRejected"
      | "PropertyVerified"
      | "TransferInitiated"
      | "TransferRejected"
      | "Unpaused"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerProperties",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPropertyDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "governmentAuthority",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateTransfer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerProperties",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "properties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "propertyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "propertyPendingTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerProperty",
    values: [string, string, BigNumberish, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectProperty",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectTransfer",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "surveyNumberExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferRequestCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateGovernmentAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProperty",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerProperties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPropertyDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governmentAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerProperties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "properties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "propertyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "propertyPendingTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "surveyNumberExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferRequestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateGovernmentAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProperty",
    data: BytesLike
  ): Result;
}

export namespace GovernmentAuthorityUpdatedEvent {
  export type InputTuple = [
    oldAuthority: AddressLike,
    newAuthority: AddressLike
  ];
  export type OutputTuple = [oldAuthority: string, newAuthority: string];
  export interface OutputObject {
    oldAuthority: string;
    newAuthority: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [
    transferId: BigNumberish,
    propertyId: BigNumberish,
    oldOwner: AddressLike,
    newOwner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    transferId: bigint,
    propertyId: bigint,
    oldOwner: string,
    newOwner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    transferId: bigint;
    propertyId: bigint;
    oldOwner: string;
    newOwner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyRegisteredEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    owner: AddressLike,
    surveyNumber: string,
    propertyType: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: bigint,
    owner: string,
    surveyNumber: string,
    propertyType: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: bigint;
    owner: string;
    surveyNumber: string;
    propertyType: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyRejectedEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    rejectedBy: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    propertyId: bigint,
    rejectedBy: string,
    reason: string
  ];
  export interface OutputObject {
    propertyId: bigint;
    rejectedBy: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyVerifiedEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    verifiedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: bigint,
    verifiedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: bigint;
    verifiedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferInitiatedEvent {
  export type InputTuple = [
    transferId: BigNumberish,
    propertyId: BigNumberish,
    fromOwner: AddressLike,
    toOwner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    transferId: bigint,
    propertyId: bigint,
    fromOwner: string,
    toOwner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    transferId: bigint;
    propertyId: bigint;
    fromOwner: string;
    toOwner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRejectedEvent {
  export type InputTuple = [
    transferId: BigNumberish,
    propertyId: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    transferId: bigint,
    propertyId: bigint,
    reason: string
  ];
  export interface OutputObject {
    transferId: bigint;
    propertyId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PropertyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PropertyRegistry;
  waitForDeployment(): Promise<this>;

  interface: PropertyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  approveTransfer: TypedContractMethod<
    [_transferId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getOwnerProperties: TypedContractMethod<
    [_owner: AddressLike],
    [bigint[]],
    "view"
  >;

  getPendingTransfer: TypedContractMethod<
    [_propertyId: BigNumberish],
    [PropertyRegistry.TransferRequestStructOutput],
    "view"
  >;

  getPropertyDetails: TypedContractMethod<
    [_propertyId: BigNumberish],
    [PropertyRegistry.PropertyStructOutput],
    "view"
  >;

  governmentAuthority: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [_governmentAuthority: AddressLike],
    [void],
    "nonpayable"
  >;

  initiateTransfer: TypedContractMethod<
    [_propertyId: BigNumberish, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  ownerProperties: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  properties: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        boolean,
        bigint,
        bigint,
        string
      ] & {
        propertyId: bigint;
        surveyNumber: string;
        location: string;
        areaInSqFt: bigint;
        currentOwner: string;
        ipfsDocumentHash: string;
        isVerified: boolean;
        registrationTimestamp: bigint;
        propertyType: bigint;
        description: string;
      }
    ],
    "view"
  >;

  propertyCount: TypedContractMethod<[], [bigint], "view">;

  propertyPendingTransfer: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  registerProperty: TypedContractMethod<
    [
      _surveyNumber: string,
      _location: string,
      _areaInSqFt: BigNumberish,
      _ipfsHash: string,
      _propertyType: BigNumberish,
      _description: string
    ],
    [void],
    "nonpayable"
  >;

  rejectProperty: TypedContractMethod<
    [_propertyId: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;

  rejectTransfer: TypedContractMethod<
    [_transferId: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;

  surveyNumberExists: TypedContractMethod<[arg0: string], [boolean], "view">;

  transferRequestCount: TypedContractMethod<[], [bigint], "view">;

  transferRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, boolean, boolean, string] & {
        transferId: bigint;
        propertyId: bigint;
        fromOwner: string;
        toOwner: string;
        requestTimestamp: bigint;
        isApproved: boolean;
        isRejected: boolean;
        rejectionReason: string;
      }
    ],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateGovernmentAuthority: TypedContractMethod<
    [_newAuthority: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  verifyProperty: TypedContractMethod<
    [_propertyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveTransfer"
  ): TypedContractMethod<[_transferId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getOwnerProperties"
  ): TypedContractMethod<[_owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPendingTransfer"
  ): TypedContractMethod<
    [_propertyId: BigNumberish],
    [PropertyRegistry.TransferRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPropertyDetails"
  ): TypedContractMethod<
    [_propertyId: BigNumberish],
    [PropertyRegistry.PropertyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "governmentAuthority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_governmentAuthority: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initiateTransfer"
  ): TypedContractMethod<
    [_propertyId: BigNumberish, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ownerProperties"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "properties"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        boolean,
        bigint,
        bigint,
        string
      ] & {
        propertyId: bigint;
        surveyNumber: string;
        location: string;
        areaInSqFt: bigint;
        currentOwner: string;
        ipfsDocumentHash: string;
        isVerified: boolean;
        registrationTimestamp: bigint;
        propertyType: bigint;
        description: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "propertyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "propertyPendingTransfer"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerProperty"
  ): TypedContractMethod<
    [
      _surveyNumber: string,
      _location: string,
      _areaInSqFt: BigNumberish,
      _ipfsHash: string,
      _propertyType: BigNumberish,
      _description: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectProperty"
  ): TypedContractMethod<
    [_propertyId: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectTransfer"
  ): TypedContractMethod<
    [_transferId: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "surveyNumberExists"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, boolean, boolean, string] & {
        transferId: bigint;
        propertyId: bigint;
        fromOwner: string;
        toOwner: string;
        requestTimestamp: bigint;
        isApproved: boolean;
        isRejected: boolean;
        rejectionReason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateGovernmentAuthority"
  ): TypedContractMethod<[_newAuthority: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "verifyProperty"
  ): TypedContractMethod<[_propertyId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "GovernmentAuthorityUpdated"
  ): TypedContractEvent<
    GovernmentAuthorityUpdatedEvent.InputTuple,
    GovernmentAuthorityUpdatedEvent.OutputTuple,
    GovernmentAuthorityUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PropertyRegistered"
  ): TypedContractEvent<
    PropertyRegisteredEvent.InputTuple,
    PropertyRegisteredEvent.OutputTuple,
    PropertyRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PropertyRejected"
  ): TypedContractEvent<
    PropertyRejectedEvent.InputTuple,
    PropertyRejectedEvent.OutputTuple,
    PropertyRejectedEvent.OutputObject
  >;
  getEvent(
    key: "PropertyVerified"
  ): TypedContractEvent<
    PropertyVerifiedEvent.InputTuple,
    PropertyVerifiedEvent.OutputTuple,
    PropertyVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "TransferInitiated"
  ): TypedContractEvent<
    TransferInitiatedEvent.InputTuple,
    TransferInitiatedEvent.OutputTuple,
    TransferInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "TransferRejected"
  ): TypedContractEvent<
    TransferRejectedEvent.InputTuple,
    TransferRejectedEvent.OutputTuple,
    TransferRejectedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "GovernmentAuthorityUpdated(address,address)": TypedContractEvent<
      GovernmentAuthorityUpdatedEvent.InputTuple,
      GovernmentAuthorityUpdatedEvent.OutputTuple,
      GovernmentAuthorityUpdatedEvent.OutputObject
    >;
    GovernmentAuthorityUpdated: TypedContractEvent<
      GovernmentAuthorityUpdatedEvent.InputTuple,
      GovernmentAuthorityUpdatedEvent.OutputTuple,
      GovernmentAuthorityUpdatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(uint256,uint256,address,address,uint256)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PropertyRegistered(uint256,address,string,uint8,uint256)": TypedContractEvent<
      PropertyRegisteredEvent.InputTuple,
      PropertyRegisteredEvent.OutputTuple,
      PropertyRegisteredEvent.OutputObject
    >;
    PropertyRegistered: TypedContractEvent<
      PropertyRegisteredEvent.InputTuple,
      PropertyRegisteredEvent.OutputTuple,
      PropertyRegisteredEvent.OutputObject
    >;

    "PropertyRejected(uint256,address,string)": TypedContractEvent<
      PropertyRejectedEvent.InputTuple,
      PropertyRejectedEvent.OutputTuple,
      PropertyRejectedEvent.OutputObject
    >;
    PropertyRejected: TypedContractEvent<
      PropertyRejectedEvent.InputTuple,
      PropertyRejectedEvent.OutputTuple,
      PropertyRejectedEvent.OutputObject
    >;

    "PropertyVerified(uint256,address,uint256)": TypedContractEvent<
      PropertyVerifiedEvent.InputTuple,
      PropertyVerifiedEvent.OutputTuple,
      PropertyVerifiedEvent.OutputObject
    >;
    PropertyVerified: TypedContractEvent<
      PropertyVerifiedEvent.InputTuple,
      PropertyVerifiedEvent.OutputTuple,
      PropertyVerifiedEvent.OutputObject
    >;

    "TransferInitiated(uint256,uint256,address,address,uint256)": TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
    TransferInitiated: TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;

    "TransferRejected(uint256,uint256,string)": TypedContractEvent<
      TransferRejectedEvent.InputTuple,
      TransferRejectedEvent.OutputTuple,
      TransferRejectedEvent.OutputObject
    >;
    TransferRejected: TypedContractEvent<
      TransferRejectedEvent.InputTuple,
      TransferRejectedEvent.OutputTuple,
      TransferRejectedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
